season:
    datasource:
        master:
            url: jdbc:mysql://10.159.191.110:3308/ibook?&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false&zeroDateTimeBehavior=convertToNull
            username: root
            password: Trs7lo$3
        slaver:
            url: jdbc:mysql://10.159.191.110:3308/ibook?&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false&zeroDateTimeBehavior=convertToNull
            username: root
            password: Trs7lo$3