season:
    datasource:
       master:
           url: jdbc:mysql://10.159.63.23:3308/trs_interaction_service?master=1&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false&zeroDateTimeBehavior=convertToNull
           username: hshopuser
           password: 6vw$kx33n
       slaver:
           url: jdbc:mysql://10.159.63.25:3308/trs_interaction_service?master=1&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false&zeroDateTimeBehavior=convertToNull
           username: hshopuser
           password: 6vw$kx33n