season:
    datasource:
        master:
            url: jdbc:mysql://10.159.63.110:3308/ibook?&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false&zeroDateTimeBehavior=convertToNull
            username: testuser
            password: Us$4P3to
        slaver:
            url: jdbc:mysql://10.159.63.110:3308/ibook?&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false&zeroDateTimeBehavior=convertToNull
            username: testuser
            password: Us$4P3to