season:
  datasource:
    master:
      url: jdbc:mysql://10.159.63.75:3306/ibook?&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false&zeroDateTimeBehavior=convertToNull
      username: testuser
      password: Us$4P3to
    slaver:
      url: jdbc:mysql://10.159.63.76:3306/ibook?&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false&zeroDateTimeBehavior=convertToNull
      username: testuser
      password: Us$4P3to
ibook:
  service:
    imageUpload:
      #图片上传路径
      baseDir: /data/TRS/nas/ts_hudong/hsfile/ibook/
      #相对路径
      oppositeDir: /hsfile/ibook/
      #前置路径
      frontDir: /data/TRS/nas/ts_hudong
  #wcm原子权限校验
  admin:
    authServiceUrl: http://testw.haier.com/hshop/opendata.do
    operationCenter:
      moduleId:  150
    objType: 103
    objId: 5
    idsAdminUrl: http://testw.haier.com/ids
    adminAppName: wcm-hshop
    adminAppKey: 12345678
spring:
  redis:
    host: 10.159.63.66
    port: 6388
    password: trs28fgh
  rabbitmq:
    host: 10.159.63.66
    port: 5672
    username: haieradmin
    password: WiTrS39G
    virtualhost: /
    listener:
      direct:
        acknowledge-mode: manual   # 配置该消费者的ack方式为手动