season:
  datasource:
    master:
      url: jdbc:mysql://10.159.62.13:3306/ibook?master=1&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false&zeroDateTimeBehavior=convertToNull
      username: hshopuser
      password: 6vw$kx33n
    slaver:
      url: jdbc:mysql://10.159.62.14:3306/ibook?master=1&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false&zeroDateTimeBehavior=convertToNull
      username: hshopuser
      password: 6vw$kx33n
ibook:
  service:
    imageUpload:
      #图片上传路径
      baseDir: /data/TRS/nas/ts_hudong/hsfile/ibook/
      #相对路径
      oppositeDir: /hsfile/ibook/
      #前置路径
      frontDir: /data/TRS/nas/ts_hudong

spring:
  redis:
    cluster:
      nodes[0]: 10.159.61.150:6380
      nodes[1]: 10.159.61.150:6381
      nodes[2]: 10.159.61.150:6382
      nodes[3]: 10.159.61.151:6380
      nodes[4]: 10.159.61.151:6381
      nodes[5]: 10.159.61.151:6382
  rabbitmq:
    host: 10.159.61.150
    port: 5672
    username: haieradmin
    password: TstrS28O
    virtualhost: /