server:
  context-path: /ibook-service
  port: 7070

#logging.path: /data/TRS/ibook-service/logs

spring:
    profiles:
        active: local
    application:
        name: ibook-service

season:
    swagger:
        basePackage: com.trs.ibook.service
        title: 通用电子书服务组件API
        description: <b>通用电子书服务组件API</b><br/>
        version: 1.0-SNAPSHOT
        contactName: RayeGong
        contactEmail: gong.lei@trs.com.cn